### ISSUE TITLE
 垂直居中的一百零八种方式中文章中 一个问题

### ISSUE THREAD

**Issue by FoxDaxian** [Akiq2016/hzfe-questions-and-answers#8]
> 常用水平垂直居中方法

绝对定位（父级position: relative）

```method1（need't height and width）```

```css
/*  or inline-block  */
div {
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    right: 0;
    margin: auto;
}
```

这里还是需要宽高的吧？不然就全屏了，和```常用水平垂直居中方法```相悖了?
